name = "GaPSE"
uuid = "d1bf0294-456c-4ffb-813c-36d532d2da2e"
authors = ["Matteo Foglieni <matteo.foglieni16@gmail.com>"]
version = "0.1.0"

[deps]
AssociatedLegendrePolynomials = "2119f1ac-fb78-50f5-8cc0-dda848ebdb19"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GridInterpolations = "bb4c363b-b914-514b-8517-4eb369bc008a"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
LegendrePolynomials = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"
TwoFAST = "0dd23c3e-f403-11e8-3e11-4dddf690af97"
WignerSymbols = "9f57e263-0b3d-5e2e-b1be-24f2bb48858b"
