# -*- encoding: utf-8 -*-
#
# This file is part of GaPSE
# Copyright (C) 2022 Matteo Foglieni
#
# GaPSE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GaPSE is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GaPSE. If not, see <http://www.gnu.org/licenses/>.
#


name: Unit tests

on: [push]

#on:
#  push:
#    branches:
#      - demo


jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7']
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64]

    steps:
      - uses: actions/checkout@v2

      - name: "Set up Julia"
        # install Julia 
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}

      - name: "Cache artifacts"
        # avoid to re-install Julia packages every time 
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
            
      - name: "Build package"
        # compile the package
        uses: julia-actions/julia-buildpkg@latest

      - name: "Run unit tests"
        # run the tests 
        uses: julia-actions/julia-runtest@latest
      #- uses: julia-actions/julia-processcoverage@v1
      #- uses: codecov/codecov-action@v1
      #  with:
      #    file: lcov.info
